### ISSUE TITLE
[macOS] OpenCore - unable to set Full HD resolution

### ISSUE THREAD

**Issue by giaur500** [Coopydood/ultimate-macOS-KVM#119]
### Describe the Issue

I mounted OpenCore.qcow2, then tried to edit config.plist to set correct screen resolution for MacOS guest os (1920x1080) in my case. But there's no any screen reslution section in that file anymore.

What is preffered way to change resolution to 1080p?

### Operating System

Mint/LMDE

### Kernel

6.5

### Processor

i7-13700

### RAM (in GB)

32

### GPU(s)

Intel

### Version

0.12.2

### Branch

main

**Comment by Coopydood** [comment]
Hi, are you using GPU pass through?

**Comment by giaur500** [comment]
No, software rendering with virtual gpu. I tried other tools to run macos on kvm, it was alwasy possible to set resolution by editing config.plist. But your OpenCore version seems to be not include this setting. 

I'm not able to use GPU passthrough unfortunately.

**Comment by Coopydood** [comment]
Hi, that variable is for internal use (I.e read by other scripts). 

To change the screen resolution you have a couple options:

1. Copy a new OVMF from the resource store; in the main repo directory, run ```
cp ./resources/ovmf/OVMF_VARS_1920x1080.fd ./boot/OVMF_VARS.fd
```
replacing `1920x1080` with the supported resolution you need. 
2. You can add the resolution property to config.plist yourself. The reason you can't find it is simply because it is NOT set to anything. If you want an easy way to change it then perhaps try OpenCore configurator from within macOS. I believe it's in UEFI > Output. 
The reason it's not set to anything is so that it inherits the resolution used by the virtual BIOS - determined by that OVMF file - which is user selected during autopilot. 

Hope this helps. If you need anything else give me a shout, or join the discord. 

Cheers

**Comment by giaur500** [comment]
Thanks, I will try and report here if I get any problems. I think easiest way is to use correct OVMF_VARS

**Comment by giaur500** [comment]
Ok, it works with new .fd file. But you meant `OVMF_DIR`, not `boot`, it's set by default to /ovmf. I replaced existing file with the one called 1080p and guest is 1080p now. Thanks for a tip.
