### ISSUE TITLE
[macOS] Apple Id Login

### ISSUE THREAD

**Issue by Scrounger9726** [Coopydood/ultimate-macOS-KVM#134]
### Describe the Issue

Team wondering if anyone else is having a hard time logging into their apple account?  I've followed all of the guides and modified my S/N in config.plist.

Everytime I try to log into apple I get Verification Failed.

### Screenshots

![Screenshot From 2024-10-22 09-47-14](https://github.com/user-attachments/assets/860b91ca-0fa1-409a-aca4-f2f17b90281d)

### Operating System

Ubuntu

### Kernel

6.11.0-9-generic

### Processor

Intel(R) Core(TM) i9-14900K

### RAM (in GB)

32

### GPU(s)

580RX 4070ti

### Version

v0.12.4

### Branch

main

**Comment by eversiege** [comment]
Currently Sequoia has a problem signing in to AppleID due to some other verification that Apple do on their servers. in other words, Sequoia logins do not work through this project at this time.

My suggestion would be to install Sonoma and updating to Sequoia from there or (recommended) to stay on Sonoma at this time.

**Comment by knxwille** [comment]
> Currently Sequoia has a problem signing in to AppleID due to some other verification that Apple do on their servers. in other words, Sequoia logins do not work through this project at this time.
> 
> My suggestion would be to install Sonoma and updating to Sequoia from there or (recommended) to stay on Sonoma at this time.

Tried but doesn't work. Upgrade failed.

**Comment by H-Bylewski** [comment]
Hi, where is the config.plst file. I want to edit it but don't know where it is.

**Comment by knxwille** [comment]
> Hi, where is the config.plst file. I want to edit it but don't know where it is.

You must mount correct partiton. Look for /EFI/OC folder. It is inside of it.

![resim](https://github.com/user-attachments/assets/9036e4ad-9377-47fa-9911-c2c30a7ed5a5)

**Comment by H-Bylewski** [comment]
Hi, thanks for the reply. So I should edit it from inside the VM? I'm confused. I was trying different project before and this file was in Opencore directory.

**Comment by knxwille** [comment]
> Hi, thanks for the reply. So I should edit it from inside the VM? I'm confused. I was trying different project before and this file was in Opencore directory.

You can use clover configurator. Download and install your VM. Mount EFI partition Open config.plist edit,save and reboot. You may reset NVRAM too. 
https://mackie100projects.altervista.org/download-clover-configurator/

**Comment by H-Bylewski** [comment]
For some reason clover won't load config.plst file. It mounts EFI, file is there but all tabs in clover are empty. Anyway I used ProperTree. Why reset NVRAM for? Does this have something to do with iMessage not working? because its not :(. iCloud and store works fine bur iMessage and FaceTime won't let me sign in, kind off iMessage signs in shows empty message and signs out again. Face time just spits out error "an error occurred during authentication"

**Comment by knxwille** [comment]
> For some reason clover won't load config.plst file. It mounts EFI, file is there but all tabs in clover are empty. Anyway I used ProperTree. Why reset NVRAM for? Does this have something to do with iMessage not working? because its not :(. iCloud and store works fine bur iMessage and FaceTime won't let me sign in, kind off iMessage signs in shows empty message and signs out again. Face time just spits out error "an error occurred during authentication"

First update your opencore image.Download OpenCore.qcow2 file from here,
https://github.com/Coopydood/ultimate-macOS-KVM/tree/iCloudPatch

If you facing errors during editing you may need update clover.

**Comment by KitsuneBalloon** [comment]
FYI - Closing this issue as changes from that branch have now been merged into the dev branch.

Feel free to re-open if issues persist.
