### ISSUE TITLE
Failing to install Sonoma (Ventura installer gives me the Sonoma installer instead)

### ISSUE THREAD

**Issue by paatchii** [Coopydood/ultimate-macOS-KVM#30]
So I have been trying to get this to work but I keep getting the following error
![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/50637577/97c871db-437f-4637-b181-a8612738739a)
I have tried different file systems, trying to use Ventura instead but for some reason when I choose Ventura it downloads Sonoma instead. (This also happens with OSX-KVM)

Monterey does work but I get similar errors when trying to update to Sonoma within MacOS.

My setup:
Latest Arch Linux with zen kernel
Ryzen 7 3800x
32GB RAM
GTX 1080

**Comment by Coopydood** [comment]
> So I have been trying to get this to work but I keep getting the following error
> 
> ![image](https://github.com/Coopydood/ultimate-macOS-KVM/assets/50637577/97c871db-437f-4637-b181-a8612738739a)
> 
> I have tried different file systems, trying to use Ventura instead but for some reason when I choose Ventura it downloads Sonoma instead. (This also happens with OSX-KVM)
> 
> 
> 
> Monterey does work but I get similar errors when trying to update to Sonoma within MacOS.
> 
> 
> 
> My setup:
> 
> Latest Arch Linux with zen kernel
> 
> Ryzen 7 3800x
> 
> 32GB RAM
> 
> GTX 1080

I myself have experienced both issues also, and I'm actively investigating both. 

As for Ventura, vit9696's script is currently broken due to an Apple server change, so I'll patch it as soon as it becomes available. 

The best way to get Ventura right now is a bit tedious, as downloading the latest version of Ventura from within Monterey actually serves up the Apple Silicon only version. The way I've done it is by specifically downloading 13.6.1 which is universal. 

If you'd still like Ventura, for the time being, use this link to download 13.6.1 from within Monterey, and perform a system upgrade: https://swcdn.apple.com/content/downloads/14/43/042-82952-A_GEJ3YDGEVG/cxed0qvmvtdvuix3xskr6zz1o4nc8fwry0/InstallAssistant.pkg

Thanks a lot for taking the time to report this issue and using my project, I appreciate it!

**Comment by paatchii** [comment]
Thanks for the response! Doing the system upgrade indeed got me to Ventura so thanks a lot for that. And glad to hear that I'm not the only one with the Sonoma problems. I was pulling my hair out for 2 days haha. Hopefully it can be resolved in the future.

**Comment by Coopydood** [comment]
Hi, if you used AutoPilot to create the VM, would you mind submitting your latest AutoPilot log? It's located in <repo>/logs.

**Comment by Gucan** [comment]
There are two problems with installing Sonoma.
First, you need to change the -cpu parameter to host, otherwise it will restart indefinitely when you try to start it after installation.
Second, during online installation, I don’t know why the recovery environment will try to download the installation resources of the arm series, resulting in an error that it cannot be found. bootbase.efi, just execute the following command after the disk tool formats the partition.
```
mkdir -p /Volumes/'partition name'/private/tmp
cp -R "/Install macOS Sonoma.app" /Volumes/'partition name'/private/tmp/
mkdir "/Volumes/'partition name'/private/tmp/Install macOS Sonoma.app/Contents/SharedSupport"
curl -L -o "/Volumes/'partition name'/private/tmp/Install macOS Sonoma.app/Contents/SharedSupport/SharedSupport.dmg" https://swcdn.apple.com/content/downloads/24/37/052-09398-A_DIKZGBNOM0/y4rz9dued01dtyl65nxqgd08wj2ar5cr6v/InstallAssistant.pkg
"/Volumes/'partition name'/private/tmp/Install macOS Sonoma.app/Contents/MacOS/InstallAssistant_springboard"
```
