### ISSUE TITLE
[macOS] High Sierra can only use the mouse for initial setup on virt manager not from the main.py

### ISSUE THREAD

**Issue by zyn23** [Coopydood/ultimate-macOS-KVM#92]
### Describe the Issue

So as stated in the title I can use the mouse for first instalation when using Virtual Machine Manager but can't from the main.py script. Why is this an issue? Because when I try to install the macOS High Sierra it gives me this error
![Connection Error](https://github.com/Coopydood/ultimate-macOS-KVM/assets/43765256/71652caf-4234-4ea4-a8d1-9587b14c4c2d)
I think this is because I had to stop dnsmasq so it can't connect to the servers or the servers just stopped being available. I need to disable dnsmasq otherwise my virt manager gives me an error saying I can't connect to the network default because the address 192.168.122.1 is already being used. 
I want to use High Sierra because it supports my nvidia gtx 960 card for later passthrough.

### Reproduce the Issue

For the mouse error just run main.py and boot.
For internet error (I think it only happens because of dnsmasq stop) use virt manager with dnsmasq stopped

### Expectation

Being able to install the macOS High Sierra

### Operating System

Debian Trixie

### Kernel

6.7.12 and 6.8.7liquorx

### Processor

AMD Ryzen 5 3600

### RAM (in GB)

16GB 8GB for the vm

### GPU(s)

RX 6600 and GTX 960

### Version

v0.11.3

### Branch

main

**Comment by Coopydood** [comment]
Hey, I believe I may have implemented a fix in the upcoming release. Do you mind trying it? You'll have to regenerate your AutoPilot script but you can keep your existing hard drive files etc. 

```
./scripts/repo-update.py --force --targetBranch dev
```

**Comment by Coopydood** [comment]
If you'd like more direct support you're welcome to join the discord too. :)

**Comment by zyn23** [comment]
I updated to the dev branch and it didn't fixe the issue for me kinda weird anyway I would like to have a link to the discord server. The link on the main page doesn't seem to work for me

**Comment by LuboGD** [comment]
Not to resurrect a necro thread, but I have a workaround to deal with "The recovery server could not be contacted" problem.
See:
https://mrmacintosh.com/how-to-fix-the-recovery-server-could-not-be-contacted-error-high-sierra-recovery-is-still-online-but-broken/
Basically, once the VM is booted up to the initial install screen, you launch Terminal, and input the following:
nvram IASUCatalogURL="http://swscan.apple.com/content/catalogs/others/index-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog"
Forces the recovery/installer to use http instead of https, and the install works! The variable is saved in nvram across reboots, so if it can be added to the appropriate file in the git repo, it will solve that error for all future users, not just for High Sierra, but likely for all versions from Leopard onward. Asking developer to add to project internally, please.
Also, same download (via https, so with SSL) works fine in already installed High Sierra, so recompiling/updating relevant component of recovery.img (curl? not sure) and remastering recovery.img should also work.

**Comment by Coopydood** [comment]
That is really interesting. Would be dead easy to add to NVRAM globally. Will test it out and see if it works! If so I’ll push a 0.12.3 release and credit you. :)

Thanks a lot for bringing to my attention!

**Comment by LuboGD** [comment]
Awesome. Probably should credit the page I quoted above, not my discovery, I just applied it successfully.
Though I do have ideas how to work around such problems, like the one about fixing SSL on recovery.img if possible.
Also, recovery.img has fully functional terminal, vi, writable /tmp directory, and so on.
Should be possible to put a copy of the catalog in there, and rewrite URL to point to repo. Or put recompiled curl in there, and call it between recovery and install phase, instead of one on recovery.img

**Comment by Coopydood** [comment]
VERY happy to report that your fix DOES work! Pushing as 0.12.2 soon.

Thank you so much for bringing this to my attention - this will make NVIDIA people happy!

![image](https://github.com/user-attachments/assets/03842d5c-98ba-44e7-989f-d0bffacbec6e)

**Comment by Coopydood** [comment]
https://github.com/Coopydood/ultimate-macOS-KVM/releases/tag/v0.12.2-rc1
If you can, try testing it and see how you get on :)

**Comment by eversiege** [comment]
Made it to main branch, closing.
